"""quotation validity and notes

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 17:32:43.992769
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('quotation_validity_days', sa.Integer(), server_default='15', nullable=False))
    op.add_column('quotations', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('quotations', sa.Column('notes', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'notes')
    op.drop_column('quotations', 'valid_until')
    op.drop_column('companies', 'quotation_validity_days')
    # ### end Alembic commands ###
