"""tds on payments

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 17:45:32.577787
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount_tds', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('receipt_allocations', sa.Column('tds_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('receipts', sa.Column('tds_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('receipts', sa.Column('tds_section', sa.String(length=10), server_default='', nullable=False))
    op.add_column('receipts', sa.Column('tds_certificate_received', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'tds_certificate_received')
    op.drop_column('receipts', 'tds_section')
    op.drop_column('receipts', 'tds_amount')
    op.drop_column('receipt_allocations', 'tds_amount')
    op.drop_column('invoices', 'amount_tds')
    # ### end Alembic commands ###
