"""payment reminders

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 17:48:22.308211
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('reminders_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('companies', sa.Column('reminder_before_days', sa.Integer(), server_default='3', nullable=False))
    op.add_column('companies', sa.Column('reminder_after_days', sa.String(length=40), server_default='1,7,15,30', nullable=False))
    op.add_column('customers', sa.Column('email', sa.String(length=160), server_default='', nullable=False))
    op.add_column('customers', sa.Column('phone', sa.String(length=40), server_default='', nullable=False))
    op.add_column('invoices', sa.Column('reminder_offsets_sent', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('invoices', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'last_reminder_at')
    op.drop_column('invoices', 'reminder_offsets_sent')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'email')
    op.drop_column('companies', 'reminder_after_days')
    op.drop_column('companies', 'reminder_before_days')
    op.drop_column('companies', 'reminders_enabled')
    # ### end Alembic commands ###
