"""price lists and line discounts

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01 17:53:31.940120
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price_list_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_list_id', 'item_id', 'min_qty', name='uq_price_list_item_qty')
    )
    op.create_index(op.f('ix_price_list_items_item_id'), 'price_list_items', ['item_id'], unique=False)
    op.add_column('companies', sa.Column('default_price_list_id', sa.UUID(), nullable=True))
    op.create_foreign_key('companies_default_price_list_id_fkey', 'companies', 'price_lists', ['default_price_list_id'], ['id'])
    op.add_column('customers', sa.Column('price_list_id', sa.UUID(), nullable=True))
    op.create_foreign_key('customers_price_list_id_fkey', 'customers', 'price_lists', ['price_list_id'], ['id'])
    op.add_column('invoice_lines', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    op.add_column('quotation_lines', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    op.add_column('sales_order_lines', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order_lines', 'discount_pct')
    op.drop_column('quotation_lines', 'discount_pct')
    op.drop_column('invoice_lines', 'discount_pct')
    op.drop_constraint('customers_price_list_id_fkey', 'customers', type_='foreignkey')
    op.drop_column('customers', 'price_list_id')
    op.drop_constraint('companies_default_price_list_id_fkey', 'companies', type_='foreignkey')
    op.drop_column('companies', 'default_price_list_id')
    op.drop_index(op.f('ix_price_list_items_item_id'), table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_table('price_lists')
    # ### end Alembic commands ###
