"""gst portal references

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-01 18:16:22.123442
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('irn', sa.String(length=64), server_default='', nullable=False))
    op.add_column('invoices', sa.Column('irn_ack_no', sa.String(length=20), server_default='', nullable=False))
    op.add_column('invoices', sa.Column('irn_ack_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('eway_bill_no', sa.String(length=12), server_default='', nullable=False))
    op.add_column('invoices', sa.Column('eway_bill_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'eway_bill_date')
    op.drop_column('invoices', 'eway_bill_no')
    op.drop_column('invoices', 'irn_ack_date')
    op.drop_column('invoices', 'irn_ack_no')
    op.drop_column('invoices', 'irn')
    # ### end Alembic commands ###
