"""salesperson and target basis

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-01 18:23:31.457795
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_settings', sa.Column('target_basis', sa.String(length=10), server_default='won', nullable=False))
    op.add_column('invoices', sa.Column('salesperson_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoices_salesperson_id'), 'invoices', ['salesperson_id'], unique=False)
    op.create_foreign_key('invoices_salesperson_id_fkey', 'invoices', 'users', ['salesperson_id'], ['id'])
    op.add_column('sales_orders', sa.Column('salesperson_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sales_orders_salesperson_id'), 'sales_orders', ['salesperson_id'], unique=False)
    op.create_foreign_key('sales_orders_salesperson_id_fkey', 'sales_orders', 'users', ['salesperson_id'], ['id'])
    # Existing sales count for the deal's owner, else whoever entered the order; invoices follow their order.
    op.execute("""
        UPDATE sales_orders o SET salesperson_id = COALESCE(
            (SELECT owner_user_id FROM opportunities WHERE id = o.opportunity_id), o.created_by)
    """)
    op.execute("UPDATE invoices i SET salesperson_id = (SELECT salesperson_id FROM sales_orders WHERE id = i.order_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_orders_salesperson_id_fkey', 'sales_orders', type_='foreignkey')
    op.drop_index(op.f('ix_sales_orders_salesperson_id'), table_name='sales_orders')
    op.drop_column('sales_orders', 'salesperson_id')
    op.drop_constraint('invoices_salesperson_id_fkey', 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_salesperson_id'), table_name='invoices')
    op.drop_column('invoices', 'salesperson_id')
    op.drop_column('crm_settings', 'target_basis')
    # ### end Alembic commands ###
